version: '3.9'
services:

  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs
    ports:
      - 8888:8000
    volumes:
      - type: bind
        source: ./.docs
        target: /docs

  wallet:
    image: ghcr.io/knowledgeonwebscale/solid-web-monetization/accountant:latest
    pull_policy: always
    container_name: wallet
    ports:
      - 8081:80
    
  store:
    image: ghcr.io/knowledgeonwebscale/solid-web-monetization/microstore:latest
    pull_policy: always
    container_name: store
    ports:
      - 8082:80

  