site_name: SOLID Web Monetization Docs
theme:
  name: material
  palette:
    scheme: default
    primary: deep purple
    accent: deep orange
  logo: assets/solid-emblem.svg
  favicon: assets/solid-emblem.svg
  features:
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search
    - search.suggest

markdown_extensions:
  - abbr
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true


nav:
  - Home: index.md
  - Demo: demo/index.md
  - Components:
    - Accountant:
      - accountant/index.md
      - Practical: accountant/practical.md
      - Technical: accountant/technical.md
    - Microstore:
      - microstore/index.md
    - Web Monetization Provider:
      - wmp/index.md
      - wmp/technical.md
  - Specification: specs.html" target="_blank"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KNowledgeOnWebScale/solid-web-monetization