site_name: Solid Web Monetization Docs
site_url: https://knowledgeonwebscale.github.io/solid-web-monetization/
theme:
  name: material
  palette:
    scheme: default
    primary: deep purple
    accent: deep orange
  logo: assets/solid-emblem.svg
  favicon: assets/solid-emblem.svg
  features:
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search
    - search.suggest
    - content.code.annotate

markdown_extensions:
  - abbr
  - pymdownx.snippets
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


nav:
  - Home: index.md
  - Demo: 
    - Introduction: demo/intro.md
    - Scenario: demo/scenario.md
  - Components:
    - Accountant:
      - accountant/index.md
      - Practical: accountant/practical.md
      - Technical: accountant/technical.md
    - Microstore:
      - microstore/index.md
      - Practical: microstore/practical.md
      - Technical: microstore/technical.md
    - Web Monetization Provider:
      - wmp/index.md
      - Practical: wmp/practical.md
      - Technical: wmp/technical.md
  - Specification: spec.html" target="_blank"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KNowledgeOnWebScale/solid-web-monetization