name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PUBLIC_URL: /solid-web-monetization

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install NPM packages
      working-directory: ./solid-accountant
      run: npm ci
    
    - name: Build project
      working-directory: ./solid-accountant
      run: npm run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./solid-accountant/dist
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./solid-accountant/dist

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./solid-accountant/dist
        destination_dir: wallet