name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-root-page:
    name: Build root page
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: /solid-web-monetization
    steps:
      - uses: actions/checkout@v2
      - name: Deploy rootpage to gh-pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.htmlroot
    

  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    needs: build-root-page
    env:
      PUBLIC_URL: /solid-web-monetization/docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build
        working-directory: ./.docs
      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docs/site
          destination_dir: docs
    

  build-accountant:
    name: Build accountant
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PUBLIC_URL: /solid-web-monetization/wallet
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install accountant yarn packages
      working-directory: ./solid-accountant
      run: yarn
    
    - name: Build accountant project
      working-directory: ./solid-accountant
      run: yarn run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: accountant-production-files
        path: ./solid-accountant/dist
    
  build-microstore:
    name: Build microstore
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PUBLIC_URL: /solid-web-monetization/store
    steps:    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install microstore yarn packages
      working-directory: ./solid-microstore
      run: yarn

    - name: Build microstore project
      working-directory: ./solid-microstore
      run: yarn run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: microstore-production-files
        path: ./solid-microstore/dist

  deploy-accountant:
    name: Deploy accountant 
    needs: [build-accountant, build-docs]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      PUBLIC_URL: /solid-web-monetization/wallet
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: accountant-production-files
        path: ./solid-accountant/dist

    - name: Deploy accountant to gh-pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./solid-accountant/dist
        destination_dir: wallet
  
  deploy-microstore:
    name: Deploy microstore 
    needs: [build-microstore, deploy-accountant]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      PUBLIC_URL: /solid-web-monetization/store
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: microstore-production-files
        path: ./solid-microstore/dist

    - name: Deploy microstore to gh-pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./solid-microstore/dist
        destination_dir: store
