name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:

  # build-root-page:
  #   name: Build root page
  #   runs-on: ubuntu-latest
  #   env:
  #     PUBLIC_URL: /solid-web-monetization
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy rootpage to gh-pages
  #       uses: peaceiris/actions-gh-pages@v3.8.0
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./.htmlroot
    

  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    needs: build-root-page
    env:
      PUBLIC_URL: /solid-web-monetization
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build
        working-directory: ./.docs
      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docs/site    

  build-accountant:
    name: Build accountant
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PUBLIC_URL: /solid-web-monetization/wallet
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install accountant yarn packages
      working-directory: ./solid-accountant
      run: yarn
    
    - name: Build accountant project
      working-directory: ./solid-accountant
      run: yarn run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: accountant-production-files
        path: ./solid-accountant/dist

  build-wmp:
    name: Build WMP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16 for deploy to GitHub Container Registry
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Build docker with jib
      run: mvn package
      working-directory: ./solid-wmp
      env:
        REGISTRY_USERNAME: ${{ github.actor }}
        REGISTRY_PASSWORD: ${{ github.token }}

  docker-accountant:
    name: Dockerize accountant
    needs: [build-accountant]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: accountant-production-files
        path: ./solid-accountant/dist
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta-wallet
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/accountant
        tags: latest
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./solid-accountant
        file: ./solid-accountant/docker/Dockerfile
        push: true
        tags: ${{ steps.meta-wallet.outputs.tags }}
    
  build-microstore:
    name: Build microstore
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PUBLIC_URL: /solid-web-monetization/store
    steps:    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install microstore yarn packages
      working-directory: ./solid-microstore
      run: yarn

    - name: Build microstore project
      working-directory: ./solid-microstore
      run: yarn run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: microstore-production-files
        path: ./solid-microstore/dist

  docker-microstore:
    name: Dockerize microstore
    needs: [build-microstore]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: microstore-production-files
        path: ./solid-microstore/dist
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta-store
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/microstore
        tags: latest
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./solid-microstore
        file: ./solid-microstore/docker/Dockerfile
        push: true
        tags: ${{ steps.meta-store.outputs.tags }}